Compute start and end offsets from timestamps
deviceinsight/kafkactl pull request #147
Opened 2023-02-27 18:13 UTC by faillefer

# Description

This PR is based on PR #126 by @nanic (Thanks for the work !)
Implements #121

I've added integration tests and updated the code so that '--exit' is not mandatory when using --from-timestamp
I've had to rework getOffsetBounds method to better manage possible options 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Documentation

- [ ] the change is mentioned in the `## [Unreleased]` section of `CHANGELOG.md`
- [x] the configuration yaml was changed and the example config in `README.md` was updated
- [x] a usage example was added to `README.md`
- [x] tests for the changes have been implemented (see: [Testing your changes](https://github.com/deviceinsight/kafkactl/blob/main/.github/contributing.md#testing-your-changes))

2023-03-02 08:04 UTC, d-rk requested changes
Generally the PR looks good :+1: 
I found mainly minor issues. The only thing that I like to be added is the parsing of different timestamp formats.

2023-03-02 08:04 UTC, d-rk commented on util/util.go
> +func StrArrayEqual(a, b []string) bool {
```suggestion
func StringArraysEqual(a, b []string) bool {
```

2023-03-02 21:52 UTC, faillefer commented
Thanks for this very complete review and for the proposed improvements :smiley:. I think they are all implemented in the last commits. 
It would be helpful to update the readme.md with supported timestamp/date formats. But shall we use "examples" to describe them (as in Go time package) or a more standard pattern (like yyyy-MM-dd'T'HH:mm:ss.SSS)

2023-03-06 06:53 UTC, merged

2023-03-06 06:53 UTC, d-rk commented
thank you for the PR @faillefer :+1: